#!/bin/sh

cd "`dirname $0`"

url="https://happening.im/plugin/${1-$(cat .deploykey)}"
if [ $? -ne 0 ]; then
	echo "Either supply a deploy key as first argument or populate .deploykey"
	exit 1
fi

tmp=.upload.zip

# see if we can use curl, otherwise try wget, else fail
if hash curl 2> /dev/null; then
	curl --data-binary @$tmp ${url}
elif hash wget 2> /dev/null; then
	wget --content-on-error --post-file=$tmp ${url} -O - -q
else
	echo "This script requires either 'curl' or 'wget' in your path. Hint: apt-get install curl" >&2
	rm -f $tmp
	exit 1
fi


